# To install the git pre-commit hook run:
#   pre-commit install
# To update the pre-commit hooks run:
#   pre-commit install-hooks
exclude: '^(\.tox|ci/templates|\.bumpversion\.cfg)(/|$)'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: trailing-whitespace
{%- if cookiecutter.c_extension_support == 'cython' %}
        exclude_types:
          - c
{%- endif %}
      - id: end-of-file-fixer
{%- if cookiecutter.c_extension_support == 'cython' %}
        exclude_types:
          - c
{%- endif %}
      - id: debug-statements
  - repo: https://github.com/timothycrosley/isort
    rev: master
    hooks:
      - id: isort
{%- if cookiecutter.pre_commit_formatter == 'yapf' %}
  - repo: https://github.com/google/yapf
    rev: main
    hooks:
      - id: yapf
{%- elif cookiecutter.pre_commit_formatter == 'black' %}
  - repo: https://github.com/psf/black
    rev: main
    hooks:
      - id: black
{%- elif cookiecutter.pre_commit_formatter == 'blue' %}
  - repo: https://github.com/grantjenks/blue
    rev: master
    hooks:
      - id: blue
{%- endif %}
{%- if cookiecutter.linter == "flake8" %}
  - repo: https://github.com/pycqa/flake8
    rev: master
    hooks:
      - id: flake8
{%- endif %}